version: "3.9"

services:
  app:
    command: nodemon index.js
    container_name: docker_watch
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app # to mount local folder in container
      - /usr/src/app/node_modules # npm install doesn't work without it
    ports:
      - 3000:3000
